/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/customer": {
    get: operations["getCustomers"];
    post: operations["createCustomer"];
  };
  "/customer/{customerId}": {
    get: operations["getCustomerById"];
    delete: operations["deleteCustomerById"];
    patch: operations["updateCustomerById"];
  };
  "/product": {
    get: operations["getProducts"];
    post: operations["createProduct"];
  };
  "/product/{productCode}": {
    get: operations["getProductByProductCode"];
    delete: operations["deleteProductById"];
    patch: operations["updateProductByProductCode"];
  };
}

export interface components {
  schemas: {
    Error: {
      error_code: number;
      error_message: string;
    };
    Customer: {
      customerId?: components["schemas"]["customerId"];
      name: string;
      /** Format: email */
      email: string;
      address?: string | null;
      phone?: string | null;
      active?: boolean;
      createdAt?: components["schemas"]["datetime"];
      updatedAt?: components["schemas"]["datetime"];
    };
    Product: {
      productId?: components["schemas"]["productId"];
      productCode: components["schemas"]["productCode"];
      name: string;
      description?: string | null;
      price: string;
      active?: boolean;
      createdAt?: components["schemas"]["datetime"];
      updatedAt?: components["schemas"]["datetime"];
    };
    /**
     * Format: date-time
     * @description date time of the entity
     */
    datetime: Date;
    /**
     * Format: uuid
     * @description Unique identifier of the customer
     * @example a75048e9-a243-4661-8c4b-f95b7cc25437
     */
    customerId: string;
    /**
     * Format: uuid
     * @description Unique identifier of the product
     */
    productId: string;
    productCode: string;
  };
}

export interface operations {
  getCustomers: {
    responses: {
      /** Get all customers */
      200: {
        content: {
          "application/json": components["schemas"]["Customer"][];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      409: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  createCustomer: {
    responses: {
      /** Created customer datas */
      201: {
        content: {
          "application/json": components["schemas"]["Customer"];
        };
      };
      /** Failed request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      409: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
    /** To create new customer */
    requestBody: {
      content: {
        "application/json": components["schemas"]["Customer"];
      };
    };
  };
  getCustomerById: {
    parameters: {
      path: {
        customerId: components["schemas"]["customerId"];
      };
    };
    responses: {
      /** Get customer by ID */
      200: {
        content: {
          "application/json": components["schemas"]["Customer"];
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      409: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  deleteCustomerById: {
    parameters: {
      path: {
        customerId: components["schemas"]["customerId"];
      };
    };
    responses: {
      /** Sucessfully deleted customer */
      204: never;
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      409: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  updateCustomerById: {
    parameters: {
      path: {
        customerId: components["schemas"]["customerId"];
      };
    };
    responses: {
      /** updated customer response */
      200: {
        content: {
          "application/json": components["schemas"]["Customer"];
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      409: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
    /** JSON object to update customer */
    requestBody: {
      content: {
        "application/json": components["schemas"]["Customer"];
      };
    };
  };
  getProducts: {
    responses: {
      /** Get all products */
      200: {
        content: {
          "application/json": components["schemas"]["Product"][];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      409: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  createProduct: {
    responses: {
      /** Created product datas */
      201: {
        content: {
          "application/json": components["schemas"]["Product"];
        };
      };
      /** Failed request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      409: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
    /** To create new product */
    requestBody: {
      content: {
        "application/json": components["schemas"]["Product"];
      };
    };
  };
  getProductByProductCode: {
    parameters: {
      path: {
        productCode: components["schemas"]["productCode"];
      };
    };
    responses: {
      /** Get product by productcode */
      200: {
        content: {
          "application/json": components["schemas"]["Product"];
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      409: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  deleteProductById: {
    parameters: {
      path: {
        productCode: components["schemas"]["productCode"];
      };
    };
    responses: {
      /** Sucessfully deleted product */
      204: never;
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      409: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  updateProductByProductCode: {
    parameters: {
      path: {
        productCode: components["schemas"]["productCode"];
      };
    };
    responses: {
      /** updated product response */
      200: {
        content: {
          "application/json": components["schemas"]["Product"];
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      409: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
    /** JSON object to update product */
    requestBody: {
      content: {
        "application/json": components["schemas"]["Product"];
      };
    };
  };
}

export interface external {}
