/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/customer": {
    get: operations["getCustomers"];
    post: operations["createCustomer"];
  };
  "/customer/{customerId}": {
    get: operations["getCustomerById"];
  };
}

export interface components {
  schemas: {
    Error: {
      error_code: number;
      error_message: string;
    };
    Customer: {
      customerId?: string;
      name: string;
      email: string;
      address?: string | null;
      phone?: string | null;
      createdAt?: components["schemas"]["datetime"];
      updatedAt?: components["schemas"]["datetime"];
    };
    /**
     * Format: date-time
     * @description date time of the entity
     */
    datetime: Date;
  };
}

export interface operations {
  getCustomers: {
    responses: {
      /** Get all customers */
      200: {
        content: {
          "application/json": components["schemas"]["Customer"][];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      409: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  createCustomer: {
    responses: {
      /** Created customer datas */
      200: {
        content: {
          "application/json": components["schemas"]["Customer"];
        };
      };
      /** Failed request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      409: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
    /** To create new customer */
    requestBody: {
      content: {
        "application/json": components["schemas"]["Customer"];
      };
    };
  };
  getCustomerById: {
    parameters: {
      path: {
        customerId: string;
      };
    };
    responses: {
      /** Get customer by ID */
      200: {
        content: {
          "application/json": components["schemas"]["Customer"];
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      409: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
}

export interface external {}
